
AMP_ENABLE: False
DISCRETE_MODEL:
   TYPE: clip
   NAME: clip_RN50
#   DROP_PATH_RATE: 0.2
#   RESNET:
#     Z_CHANNELS: 512

DATA:
  IMG_SIZE: 224

#TRAIN: # follow this code https://github.com/pytorch/examples/tree/main/imagenet
#  BASE_LR: 
#  WEIGHT_DECAY:
#  OPTIMIZER:
#    NAME: SGD
#    MOMENTUM: 
